package generatedbyassl.as.aes.vm_instance.aeself_management.self_configuring;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'InRunningVm' (specified as FLUENT ASSL tier).
 */
public class INRUNNINGVM
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INRUNNINGVM' class.
	 */
	static private INRUNNINGVM oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INRUNNINGVM (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.vm_instance.events.TIMETORUNVM.getInstance() );
		generatedbyassl.as.aes.vm_instance.events.TIMETORUNVM.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.vm_instance.events.VMSTARTED.getInstance() );
		generatedbyassl.as.aes.vm_instance.events.VMSTARTED.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INRUNNINGVM' class.
	 */
	static public INRUNNINGVM getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INRUNNINGVM();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}