package generatedbyassl.as.aes.controller.aeself_management.self_healing;

import java.io.Serializable;
import generatedbyassl.as.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'InRepairing' (specified as FLUENT ASSL tier).
 */
public class INREPAIRING
	extends ASSLFLUENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'INREPAIRING' class.
	 */
	static private INREPAIRING oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  INREPAIRING (  )
	{
		vInitiatedByEvents.add( generatedbyassl.as.aes.controller.events.RUNNINGSTATES.getInstance() );
		generatedbyassl.as.aes.controller.events.RUNNINGSTATES.getInstance().addEventCatcher(this); //**** fluent registers for that event
		vTerminatedByEvents.add( generatedbyassl.as.aes.controller.events.REPAIRINGDONE.getInstance() );
		generatedbyassl.as.aes.controller.events.REPAIRINGDONE.getInstance().addEventCatcher(this); //**** fluent registers for that event
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'INREPAIRING' class.
	 */
	static public INREPAIRING getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new INREPAIRING();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method calls all the fluent-mapped actions in sequence.
	 */
	protected synchronized void callFluentActions (  )
	{
	}

}