package generatedbyassl.as.aes.vm_instance.aeip.managed_elements;

import java.io.Serializable;
import generatedbyassl.as.ASSLMANAGED_ELEMENT;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'VM_INSTANCE_Interface' (specified as MANAGED_ELEMENT ASSL tier).
 */
public class VM_INSTANCE_INTERFACE
	extends ASSLMANAGED_ELEMENT
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'VM_INSTANCE_INTERFACE' class.
	 */
	static private VM_INSTANCE_INTERFACE oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  VM_INSTANCE_INTERFACE (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'VM_INSTANCE_INTERFACE' class.
	 */
	static public VM_INSTANCE_INTERFACE getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new VM_INSTANCE_INTERFACE();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void SUSPEND (  )
	{
		//**** Implement this method.
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void STOP (  )
	{
		//**** Implement this method.
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Management element interface function.
	 */
	public void TERMINATE (  )
	{
		//**** Implement this method.
	}

}