package generatedbyassl.as.aes;

import java.io.Serializable;
import generatedbyassl.as.ASSLAE;
import generatedbyassl.as.aes.vm_instance.controlloop.*;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'VM_INSTANCE' (specified as AE ASSL tier).
 */
public class VM_INSTANCE
	extends ASSLAE
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'VM_INSTANCE' class.
	 */
	static private VM_INSTANCE oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's monitor.
	 */
	private VM_INSTANCE_ASSLMONITOR oMonitor = new VM_INSTANCE_ASSLMONITOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's analyzer.
	 */
	private VM_INSTANCE_ASSLANALYZER oAnalyzer = new VM_INSTANCE_ASSLANALYZER();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's simulator.
	 */
	private VM_INSTANCE_ASSLSIMULATOR oSimulator = new VM_INSTANCE_ASSLSIMULATOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AE control loop's executor.
	 */
	private VM_INSTANCE_ASSLEXECUTOR oExecutor = new VM_INSTANCE_ASSLEXECUTOR();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the FRIENDS class.
	 */
	public generatedbyassl.as.aes.vm_instance.FRIENDS FRIENDS = generatedbyassl.as.aes.vm_instance.FRIENDS.getInstance();
	/**
	 * Generated by ASSL Framework
	 * 
	 * Holds a reference to the AEIP class.
	 */
	public generatedbyassl.as.aes.vm_instance.AEIP AEIP = generatedbyassl.as.aes.vm_instance.AEIP.getInstance();

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  VM_INSTANCE (  )
	{
		vPolicies.put( "SELF_CONFIGURING", generatedbyassl.as.aes.vm_instance.aeself_management.SELF_CONFIGURING.getInstance() );
		vPolicies.put( "SELF_HEALING", generatedbyassl.as.aes.vm_instance.aeself_management.SELF_HEALING.getInstance() );
		ACTIONS.put( "RUNVM", generatedbyassl.as.aes.vm_instance.actions.RUNVM.getInstance() );
		ACTIONS.put( "REQUESTLIFECYCLE", generatedbyassl.as.aes.vm_instance.actions.REQUESTLIFECYCLE.getInstance() );
		ACTIONS.put( "MODIFYSTATE", generatedbyassl.as.aes.vm_instance.actions.MODIFYSTATE.getInstance() );
		EVENTS.put( "TIMETORUNVM", generatedbyassl.as.aes.vm_instance.events.TIMETORUNVM.getInstance() );
		EVENTS.put( "VMSTARTED", generatedbyassl.as.aes.vm_instance.events.VMSTARTED.getInstance() );
		EVENTS.put( "LIFECYCLEREQUESTED", generatedbyassl.as.aes.vm_instance.events.LIFECYCLEREQUESTED.getInstance() );
		EVENTS.put( "TIMETOSTATESIMULATION", generatedbyassl.as.aes.vm_instance.events.TIMETOSTATESIMULATION.getInstance() );
		EVENTS.put( "STATESIMULATED", generatedbyassl.as.aes.vm_instance.events.STATESIMULATED.getInstance() );
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'VM_INSTANCE' class.
	 */
	static public VM_INSTANCE getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new VM_INSTANCE();
		}
		return oInstance;
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Sets the control loop components.
	 */
	protected void setControlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		oMonitor.setMonitoredSLO(AESLO);
		oMonitor.setMonitoredMetrics(METRICS);
		oMonitor.setAnalyzer(oAnalyzer);
		oAnalyzer.setSimulator(oSimulator);
		oAnalyzer.setExecutor(oExecutor);
		oSimulator.setExecutor(oExecutor);
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * Performs the AE control loop.
	 */
	protected void controlLoop (  )
	{
		//**** This method overrides the super class's method.
		//****************************************************
		try
		{
			//**** control loops should not be very resource-consuming, thus it releases CPU for a while
			Thread.sleep(1000);
		}
		catch ( InterruptedException ex ) 
		{
			System.err.println( ex.getMessage() );
		}
		//**** performs AE control loop monitor-analyzer-simulator-executor
		oMonitor.perform();
		oAnalyzer.perform();
		oSimulator.perform();
		oExecutor.perform();
		//**** applies all the "switched-on" self-management policies for the AS
		applayPolicies();
	}

}