package generatedbyassl.as.aes.controller.aeip.messages;

import java.io.Serializable;
import generatedbyassl.as.ASSLMESSAGE;

/**
 * Generated by ASSL Framework
 * 
 * This is the Java class generated for 'msgTerminate' (specified as MESSAGE ASSL tier).
 */
public class MSGTERMINATE
	extends ASSLMESSAGE
	implements  Serializable
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * This is a reference to the unique instance of 'MSGTERMINATE' class.
	 */
	static private MSGTERMINATE oInstance = null;
	/**
	 * Generated by ASSL Framework
	 * 
	 * Needed by the class because it implements the Serializable interface.
	 */
	static final long serialVersionUID = 0001L;

	/**
	 * Generated by ASSL Framework
	 * 
	 * Because this is a singleton class its constructor is private.
	 */
	private  MSGTERMINATE (  )
	{
	}

	/**
	 * Generated by ASSL Framework
	 * 
	 * This method returns the unique instance of 'MSGTERMINATE' class.
	 */
	static public MSGTERMINATE getInstance (  )
	{
		if ( null == oInstance ) 
		{
			oInstance = new MSGTERMINATE();
		}
		return oInstance;
	}

}