package generatedbyassl.as.aes.vm_instance.controlloop;

import generatedbyassl.as.controlloop.ASSLEXECUTOR;

/**
 * Generated by ASSL Framework
 * 
 * This is the executor class of the vm_instance's control loop. An instance of this class participates in the monitor-analyzer-simulator-executor control loop of vm_instance.
 */
public class VM_INSTANCE_ASSLEXECUTOR
	extends ASSLEXECUTOR
{

	/**
	 * Generated by ASSL Framework
	 * 
	 * The superclass ASSLEXECUTOR makes this class fully functional. Put your modifications here (if any).
	 */

}